export enum TokenType {
    // Minduscript关键字
    MACRO = 1, // macro
    RETURN,
    IF, // if
    ELSE, // else
    FOR, // for
    WHILE, // while
    CONTINUE, // continue
    BREAK, // break
    IMPORT, // import
    AS, // as
    FROM, // from
    LET, // let
    CONST, // const
    BIND, // bind
    // Minduscript运算符
    ASSIGN, // =
    ADD_ASSIGN, // +=
    SUB_ASSIGN, // -=
    MUL_ASSIGN, // *=
    DIV_ASSIGN, // /=
    IDIV_ASSIGN, // //=
    MOD_ASSIGN, // %=
    POW_ASSIGN, // **=
    AND_ASSIGN, // &&=
    SHL_ASSIGN, // <<=
    SHR_ASSIGN, // >>=
    BITAND_ASSIGN, // &=
    BITOR_ASSIGN, // |=
    XOR_ASSIGN, // ^=
    OR, // ||
    OR_ASSIGN, // ||=
    NOT, // !
    // Mindustry关键字
    MAX, // max
    MIN, // min
    ANGLE, // angle
    ANGLE_DIFF, // angleDiff
    LEN, // len
    NOISE, // noise
    ABS, // abs
    LOG, // log
    LOG10, // log10
    FLOOR, // floor
    CEIL, // ceil
    SQRT, // sqrt
    RAND, // rand
    SIN, // sin
    COS, // cos
    TAN, // tan
    ASIN, // asin
    ACOS, // acos,
    ATAN, // atan
    READ, // read
    WRITE, // write
    DRAW_CLEAR, // drawClear
    DRAW_COLOR, // drawColor
    DRAW_COL, // drawCol
    DRAW_STROKE, // drawStroke
    DRAW_LINE, // drawLine
    DRAW_RECT, // drawRect
    DRAW_LINE_RECT, // drawLineRect
    DRAW_POLY, // drawPoly
    DRAW_LINE_POLY, // drawLinePoly
    DRAW_TRIANGLE, // drawTriangle
    DRAW_IMAGE, // drawImage
    PRINT, // print
    DRAW_FLUSH, // drawFlush
    PRINT_FLUSH, // printFlush
    GET_LINK, // getLink
    SET_ENABLED, // setEnabled
    SET_SHOOT, // setShoot
    SET_SHOOT_P, // setShootP
    SET_CONFIG, // setConfig
    SET_COLOR, // setColor
    RADAR, // radar
    SENSOR, // sensor
    PACK_COLOR, // packColor
    WAIT, // wait
    CPU_STOP, // cpuStop
    UNIT_BIND, // unitBind
    UNIT_RADAR, // unitRadar
    UNIT_LOCATE, // unitLocate
    IDLE, // idle
    STOP, // stop
    MOVE, // move
    APPROACH, // approach
    PATH_FIND, // pathFind
    AUTO_PATH_FIND, // autoPathFind
    BOOST, // boost
    TARGET, // target
    TARGET_P, // targetP
    ITEM_DROP, // itemDrop
    ITEM_TAKE, // itemTake
    PAY_DROP, // payDrop
    PAY_TAKE, // payTake
    PAY_ENTER, // payEnter
    MINE, // mine
    FLAG, // flag
    BUILD, // build
    GET_BLOCK, // getBlock
    WITHIN, // within
    UNBIND, // unbind
    NULL, // null
    TRUE, // true
    FALSE, // false
    ANY, // Any
    ENEMY, // Enemy
    ALLY, // Ally
    PLAYER, // Player
    ATTACKER, // Attacker
    FLYING, // Flying
    BOSS, // Boss
    GROUND, // Ground
    DISTANCE, // Distance
    HEALTH, // Health
    SHIELD, // Shield
    ARMOR, // Armor
    MAX_HEALTH, // MaxHealth
    ORE, // Ore
    BUILDING, // Building
    SPAWN, // Spawn
    DAMAGED, // Damaged
    CORE, // Core
    STORAGE, // Storage
    GENERATOR, // Generator
    TURRET, // Turret
    FACTORY, // Factory
    REPAIR, // Repair
    BATTERY, // Battery
    REACTOR, // Reactor
    // Mindustry运算符
    ADD, // +
    SUB, // -
    MUL, // *
    DIV, // /
    IDIV, // //
    MOD, // %
    POW, // **
    EQ, // ==
    NE, // !=
    AND, // &&
    LESS, // <
    LE, // <=
    GREATER, // >
    GE, // >=
    STRICT_EQ, // ===
    SHL, // <<
    SHR, // >>
    BITOR, // |
    BITAND, // &
    XOR, // ^
    FLIP, // ~
    // 其他
    IDENTIFIER, // 标识符
    MINDUSTRY_IDENTIFIER, // Mindustry标识符
    NUMBER, // 数字字面量
    STRING, // 字符串字面量
    COLOR, // 颜色
    L_BRACE, // {
    R_BRACE, // }
    L_PAREN, // (
    R_PAREN, // )
    COMMA, // ,
    SEMICOLON, // ;
}

export type Token = {
    type: TokenType;
    raw: string;
    row: number;
    col: number;
};
